version: '3'

services:
  app:
    build:
      context: node
    image: brenobattaglin/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - challenge-nnm
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    image: brenobattaglin/nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s nginx -g 'daemon off;'
    container_name: nginx
    networks:
      - challenge-nnm
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=node_challenge_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-nnm
    platform: linux/amd64

networks:
  challenge-nnm:
    driver: bridge
